# Dev version
version: '3.6'
services:

  mysql:
    container_name: "mysql"
    image: mysql
    restart: on-failure
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - datas_dev:/var/lib/mysql

  phpmyadmin:
    container_name: "phpmyadmin"
    image: phpmyadmin
    restart: on-failure
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      PMA_HOSTS: mysql

  php:
    container_name: "php"
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    restart: on-failure
    volumes:
      - ./apps/api/:${APP_VOLUME}
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - mysql


  maildev:
    container_name: "maildev"
    image: djfarrelly/maildev
    restart: on-failure
    ports:
      - 1080:80
      - 1025:25

  # node-test:
  #   container_name: "node-test"
  #   stdin_open: true
  #   build:
  #     context: .
  #     dockerfile: ./docker/node/dev/Dockerfile
  #   restart: on-failure
  #   ports:
  #     - 80:3000
  #   volumes:
  #     - ./apps/front/:${APP_VOLUME}

volumes:
  datas_dev:
    driver: local
